// @index(['./*/**','./*.ts', '!./**/*.{spec.ts,html,css,scss,stories.ts}'], f => `export * from '${f.path}'`)
export * from './config/config.component'
export * from './create/create.component'
export * from './dashboard/dashboard.component'
export * from './delete/delete.component'
export * from './detail/detail.component'
export * from './resource.component'
export * from './resource.routes'
export * from './update/update.component'
export * from './view/view.component'
