# yaml-language-server: $schema=../../../schemas/model.schema.json
name: Product
properties:
  barcode:
    type: string
    minLength: 12
    maxLength: 14
    inputType: text

  name:
    type: string
    inputType: text

  description:
    type: string
    maxLength: 300
    inputType: text

relations:
  category:
    type: sub
    target: Category

  features:
    type: subs
    target: Feature

# Add required properties
required:
  - name
  - barcode

# Add unique properties
unique:
  - name
  - barcode
