# yaml-language-server: $schema=../../../schemas/model.schema.json
name: User
properties:
  firstName:
    type: string
    minLength: 3
    maxLength: 30
    inputType: text

  lastName:
    type: string
    minLength: 3
    maxLength: 30
    inputType: text

  username:
    type: string
    format: email
    inputType: email

  password:
    type: string
    format: password
    inputType: password

unique:
  - username

required:
  - firstName
  - lastName
  - username
  - password
